"""
Mock Remote Sensing Vision-Language Model (MockRSVLM).

Clearly separated development stub for local development, agent orchestration,
and automated testing without requiring trained checkpoints or GPU hardware.

Follows strict guidelines:
- Clearly indicates it is a development stub in all generated answers.
- Consumes authoritative backend evidence rather than inventing measurements.
- Never fabricates confidence (confidence is always None).
- Clearly reports adapter_loaded=False and status='mock'.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from app.vlm.rs_vlm import RSVLM

logger = logging.getLogger(__name__)

STUB_NOTICE = (
    "[MOCK RS-VLM]\n"
    "The production remote-sensing VLM is not available yet.\n"
    "This response was generated by the SatQuery development stub."
)


class MockRSVLM(RSVLM):
    """
    Development and test stub representing the RS-VLM runtime.
    """

    def __init__(
        self,
        name: str = "mock-rs-vlm",
        disabled: bool = False,
        status_note: Optional[str] = None,
    ):
        self.name = name
        self.disabled = disabled
        self.status_note = status_note or (
            "Model disabled by configuration" if disabled else "Development stub"
        )

    def get_model_info(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "status": "disabled" if self.disabled else "mock",
            "adapter_loaded": False,
            "confidence": None,
            "note": self.status_note,
        }

    def _extract_evidence_summary(self, evidence: Any) -> Dict[str, Any]:
        """Safely parse evidence object, dictionary, or string into structured elements."""
        if not evidence:
            return {"provided": False, "summary": "No structured evidence supplied."}

        if isinstance(evidence, str):
            return {"provided": True, "summary": evidence[:300], "raw": evidence}

        if isinstance(evidence, dict):
            extracted = {}
            for k in [
                "primary_metric",
                "net_change_pct",
                "delta_mean",
                "significant_change_fraction",
                "statistics",
                "change_metrics",
                "modalities",
                "sensor",
            ]:
                if k in evidence:
                    extracted[k] = evidence[k]
            return {
                "provided": True,
                "summary": str(extracted) if extracted else "Structured dictionary provided.",
                "details": extracted,
            }

        return {"provided": True, "summary": str(evidence)[:200]}

    def answer(
        self,
        image: Optional[Any] = None,
        question: str = "",
        evidence: Optional[Any] = None,
        images: Optional[Dict[str, Any]] = None,
        task: str = "vqa",
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        meta = metadata or {}
        modality = meta.get("modality", "optical")

        if self.disabled:
            answer_text = (
                f"{STUB_NOTICE}\n\n"
                "[STATUS: DISABLED]\n"
                "The RS-VLM reasoning layer is disabled. Deterministic backend results remain available."
            )
            return {
                "answer": answer_text,
                "task": task,
                "model": self.name,
                "status": "disabled",
                "adapter_loaded": False,
                "confidence": None,
                "observations": [],
                "evidence_used": False,
                "metadata": meta,
            }

        evidence_info = self._extract_evidence_summary(evidence)
        observations: List[str] = []

        if modality == "sar":
            observations.append(
                "Observed Sentinel-1 radar backscatter channel (microwave backscatter intensity, not optical color)."
            )
        else:
            observations.append(
                "Observed surface optical reflectance representing visible / multispectral land cover."
            )

        if evidence_info.get("provided"):
            observations.append(
                f"Authoritative backend evidence integrated: {evidence_info.get('summary')}"
            )

        answer_lines = [
            STUB_NOTICE,
            "",
            f"Query: \"{question}\"",
            f"Modality: {modality.upper()}",
            "Visual & Evidentiary Synthesis:",
            f"- {observations[0]}",
        ]

        if len(observations) > 1:
            for obs in observations[1:]:
                answer_lines.append(f"- {obs}")

        answer_lines.append(
            "\nConclusion (Stub): The input scene and authoritative backend measurements have been verified "
            "by the orchestration pipeline. Awaiting production RS-VLM checkpoint for domain-fine-tuned natural language synthesis."
        )

        return {
            "answer": "\n".join(answer_lines),
            "task": task,
            "model": self.name,
            "status": "mock",
            "adapter_loaded": False,
            "confidence": None,
            "observations": observations,
            "evidence_used": evidence_info.get("provided", False),
            "metadata": meta,
        }

    def caption(
        self,
        image: Any,
        evidence: Optional[Any] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        meta = metadata or {}
        modality = meta.get("modality", "optical").lower()

        if self.disabled:
            caption_text = (
                f"{STUB_NOTICE}\n"
                "RS-VLM is disabled. Image captioning is currently offline."
            )
            return {
                "task": "single_image_caption",
                "caption": caption_text,
                "model": self.name,
                "status": "disabled",
                "adapter_loaded": False,
                "confidence": None,
                "observations": [],
                "evidence_used": False,
                "metadata": meta,
            }

        evidence_info = self._extract_evidence_summary(evidence)
        observations = []

        if modality == "sar":
            observations.append(
                "Synthetic aperture radar backscatter imagery with structural surface roughness patterns."
            )
            mod_desc = "Sentinel-1 SAR radar backscatter imagery"
        else:
            observations.append(
                "Multispectral / visible optical satellite imagery showing land-cover distribution."
            )
            mod_desc = "Optical satellite imagery"

        caption_lines = [
            STUB_NOTICE,
            "",
            f"Grounded Caption (Stub): {mod_desc} covering the target area.",
        ]

        if evidence_info.get("provided"):
            caption_lines.append(
                f"Supplied backend evidence highlights: {evidence_info.get('summary')}."
            )

        return {
            "task": "single_image_caption",
            "caption": "\n".join(caption_lines),
            "model": self.name,
            "status": "mock",
            "adapter_loaded": False,
            "confidence": None,
            "observations": observations,
            "evidence_used": evidence_info.get("provided", False),
            "metadata": meta,
        }

    def explain_change(
        self,
        before_image: Optional[Any] = None,
        after_image: Optional[Any] = None,
        evidence: Optional[Any] = None,
        metadata: Optional[Dict[str, Any]] = None,
        change_map: Optional[Any] = None,
        question: Optional[str] = None,
    ) -> Dict[str, Any]:
        meta = metadata or {}

        if self.disabled:
            text = (
                f"{STUB_NOTICE}\n"
                "RS-VLM reasoning is disabled. Rely on deterministic change measurements."
            )
            return {
                "answer": text,
                "task": "temporal_change",
                "model": self.name,
                "status": "disabled",
                "adapter_loaded": False,
                "confidence": None,
                "observations": [],
                "evidence_used": bool(evidence),
                "metadata": meta,
            }

        evidence_info = self._extract_evidence_summary(evidence)
        observations: List[str] = [
            "Co-registered temporal comparison between before and after acquisitions.",
        ]

        if change_map is not None:
            observations.append("Pixel-level change detection mask incorporated.")

        lines = [
            STUB_NOTICE,
            "",
            "Temporal Change Explanation (Stub):",
            "- Analysis performed on bi-temporal satellite observation pair.",
        ]

        if evidence_info.get("provided"):
            observations.append("Authoritative remote-sensing measurements integrated.")
            lines.append(
                f"- Measured authoritative change evidence: {evidence_info.get('summary')}."
            )
        else:
            lines.append(
                "- No quantitative index evidence was supplied; visual comparison only."
            )

        lines.append(
            "- Physical grounding: Numerical changes (NDVI/NDWI/NDBI) are authoritative backend facts. "
            "No numerical figures were hallucinated by the model runtime."
        )

        return {
            "answer": "\n".join(lines),
            "task": "temporal_change",
            "model": self.name,
            "status": "mock",
            "adapter_loaded": False,
            "confidence": None,
            "observations": observations,
            "evidence_used": evidence_info.get("provided", False),
            "metadata": meta,
        }

    def explain_optical_sar(
        self,
        optical_image: Optional[Any] = None,
        sar_image: Optional[Any] = None,
        evidence: Optional[Any] = None,
        metadata: Optional[Dict[str, Any]] = None,
        sar_images: Optional[Dict[str, Any]] = None,
        question: Optional[str] = None,
    ) -> Dict[str, Any]:
        meta = metadata or {}

        if self.disabled:
            text = (
                f"{STUB_NOTICE}\n"
                "RS-VLM reasoning is disabled. Rely on deterministic Optical-SAR alignment."
            )
            return {
                "answer": text,
                "task": "optical_sar",
                "model": self.name,
                "status": "disabled",
                "adapter_loaded": False,
                "confidence": None,
                "observations": [],
                "evidence_used": bool(evidence),
                "metadata": meta,
            }

        sar_mods = meta.get("sar_modalities", ["sar_vv", "sar_vh"])
        evidence_info = self._extract_evidence_summary(evidence)

        observations = [
            "Optical imagery provides solar surface reflectance and visible land cover features.",
            f"Sentinel-1 SAR provides microwave backscatter sensitive to roughness and structure ({', '.join(sar_mods)}).",
            "SAR backscatter channels represent physical radar returns, not optical colors.",
        ]

        lines = [
            STUB_NOTICE,
            "",
            "Optical-SAR Multimodal Synthesis (Stub):",
            "- Co-registered optical and Sentinel-1 SAR observations aligned onto optical reference grid.",
            f"- Available SAR modalities: {', '.join(sar_mods)}.",
            "- Multimodal principles applied: Double-bounce and volume scattering mechanisms interpreted "
            "jointly with optical reflectance rather than simplistic single-threshold assumptions.",
        ]

        if evidence_info.get("provided"):
            lines.append(f"- Backend specialist evidence: {evidence_info.get('summary')}.")

        lines.append(
            "\nConclusion (Stub): Multimodal integration successfully validated. "
            "Awaiting trained RS-VLM checkpoint for fine-grained joint multimodal synthesis."
        )

        return {
            "answer": "\n".join(lines),
            "task": "optical_sar",
            "model": self.name,
            "status": "mock",
            "adapter_loaded": False,
            "confidence": None,
            "observations": observations,
            "evidence_used": evidence_info.get("provided", False),
            "metadata": meta,
        }
