from pathlib import Path
from typing import Any, Dict

import numpy as np
import rasterio
from PIL import Image


def load_band(path: str) -> np.ndarray:
    """
    Load one raster band from a TIFF.
    """
    with rasterio.open(path) as src:
        return src.read(1)


def normalize_band(
    band: np.ndarray,
) -> np.ndarray:
    """
    Normalize a raster band to uint8 for visualization.
    """

    band = band.astype(np.float32)

    finite = np.isfinite(band)

    if not finite.any():
        return np.zeros(
            band.shape,
            dtype=np.uint8,
        )

    values = band[finite]

    low = np.percentile(values, 2)
    high = np.percentile(values, 98)

    if high <= low:
        return np.zeros(
            band.shape,
            dtype=np.uint8,
        )

    scaled = (
        (band - low)
        / (high - low)
    )

    scaled = np.clip(
        scaled,
        0.0,
        1.0,
    )

    scaled[~finite] = 0

    return (
        scaled * 255
    ).astype(np.uint8)


def make_rgb(
    red_path: str,
    green_path: str,
    nir_path: str,
) -> Image.Image:
    """
    Create a false-color vegetation visualization.

    R = Red
    G = Green
    B = NIR
    """

    red = normalize_band(
        load_band(red_path)
    )

    green = normalize_band(
        load_band(green_path)
    )

    nir = normalize_band(
        load_band(nir_path)
    )

    rgb = np.stack(
        [
            red,
            green,
            nir,
        ],
        axis=-1,
    )

    return Image.fromarray(
        rgb,
        mode="RGB",
    )


def load_change_map(
    visualization_path: str,
) -> Image.Image:
    """
    Load the change-map PNG generated by Person 2.
    """

    path = Path(visualization_path)

    if not path.is_absolute() and not path.exists():
        backend_dir = Path(__file__).resolve().parents[2]
        candidate = backend_dir / path
        if candidate.exists():
            path = candidate
        else:
            candidate2 = (
                backend_dir
                / "app"
                / "evidence"
                / "visualizations"
                / path.name
            )
            if candidate2.exists():
                path = candidate2

    if not path.exists():
        raise FileNotFoundError(
            f"Change-map file not found: {visualization_path}"
        )

    return Image.open(
        path
    ).convert("RGB")


def load_p2_images(
    evidence: Dict[str, Any],
) -> Dict[str, Image.Image]:
    """
    Load before/after imagery and the P2 change map.

    Returns:
        {
            "before": PIL.Image,
            "after": PIL.Image,
            "change_map": PIL.Image,
        }
    """

    images: Dict[str, Image.Image] = {}
    loaded_items: list = []

    # ---------------------------------------------------------
    # Before / after imagery
    # ---------------------------------------------------------

    p2_images = evidence.get(
        "images",
        [],
    )

    for item in p2_images:

        if not isinstance(item, dict):
            continue

        image_id = item.get(
            "id",
            "",
        )

        bands = item.get(
            "bands",
            {},
        )

        if not isinstance(bands, dict):
            continue

        required = (
            "red",
            "green",
            "nir",
        )

        if not all(
            key in bands
            for key in required
        ):
            continue

        image = make_rgb(
            red_path=bands["red"],
            green_path=bands["green"],
            nir_path=bands["nir"],
        )

        loaded_items.append((image_id, image))

    # Identify before and after imagery
    time_start = str(evidence.get("time_start") or "")
    time_end = str(evidence.get("time_end") or "")

    for img_id, img in loaded_items:
        if time_start and time_start in img_id and "before" not in images:
            images["before"] = img
        elif time_end and time_end in img_id and "after" not in images:
            images["after"] = img
        elif "2021" in img_id and "before" not in images:
            images["before"] = img
        elif "2025" in img_id and "after" not in images:
            images["after"] = img
        elif "2024" in img_id and "after" not in images:
            images["after"] = img

    # Fallback to positional assignment if not assigned by year
    if loaded_items:
        if "before" not in images:
            images["before"] = loaded_items[0][1]
        if "after" not in images and len(loaded_items) > 1:
            images["after"] = loaded_items[1][1]

    # ---------------------------------------------------------
    # Change map
    # ---------------------------------------------------------

    change_map_path = (
        evidence.get(
            "change_map_path"
        )
    )

    if change_map_path:
        try:
            images["change_map"] = (
                load_change_map(
                    change_map_path
                )
            )
        except Exception as exc:
            print(f"[P2 IMAGERY WARNING] Could not load change map: {exc}")

    return images