from pathlib import Path

from PIL import Image

from app.vlm.model import VLM
from app.vlm.evidence_builder import build_evidence


S1_DIR = Path("data/s1_visualizations")
CHANGE_MAP = Path(
    "app/evidence/visualizations/vegetation_2021_2025_change.png"
)

QUESTION = "Show vegetation change from 2021 to 2025"


def open_image(path: Path):
    if not path.exists():
        raise FileNotFoundError(
            f"Missing image: {path}"
        )

    return Image.open(path).convert("RGB")


def main():
    print("=" * 70)
    print("P4 S1 + S2 MULTIMODAL TEST")
    print("=" * 70)

    # ---------------------------------------------------------
    # Load existing S2 imagery generated by your P2 tests.
    # ---------------------------------------------------------

    before_path = Path("data/before_p2.png")
    after_path = Path("data/after_p2.png")

    before = open_image(before_path)
    after = open_image(after_path)

    # ---------------------------------------------------------
    # Load real S1 visualizations.
    # ---------------------------------------------------------

    s1_vv = open_image(
        S1_DIR / "s1_vv.png"
    )

    s1_vh = open_image(
        S1_DIR / "s1_vh.png"
    )

    # Use composite too, since it gives the VLM a joint
    # VV/VH representation.
    s1_composite = open_image(
        S1_DIR / "s1_vv_vh_composite.png"
    )

    # ---------------------------------------------------------
    # Load change map if present.
    # ---------------------------------------------------------

    change_map = None

    if CHANGE_MAP.exists():
        change_map = open_image(
            CHANGE_MAP
        )

    print("\nImages loaded:")

    print(
        "S2 before:",
        before.size,
    )

    print(
        "S2 after:",
        after.size,
    )

    print(
        "S1 VV:",
        s1_vv.size,
    )

    print(
        "S1 VH:",
        s1_vh.size,
    )

    print(
        "S1 composite:",
        s1_composite.size,
    )

    if change_map is not None:
        print(
            "Change map:",
            change_map.size,
        )

    # ---------------------------------------------------------
    # Build the same type of structured evidence that P2
    # sends to P4.
    # ---------------------------------------------------------

    backend_result = {
        "query": QUESTION,
        "plan": {
            "task": "change_detection",
            "target": "vegetation",
            "metric": "ndvi",
            "time_start": 2021,
            "time_end": 2025,
        },
        "statistics": {
            "metric": "NDVI",
            "mean_before": 0.42010581493377686,
            "mean_after": 0.30909013748168945,
            "mean_change": -0.1110156774520874,
            "changed_pixels": 5,
            "valid_pixels": 9,
            "total_pixels": 9,
            "change_ratio": 0.5555555555555556,
            "increased_pixels": 0,
            "decreased_pixels": 5,
            "change_type": "decrease",
            "threshold": 0.05,
        },
        "layers": [
            {
                "type": "change_detection",
                "name": "vegetation change map",
                "change_ratio": 0.5555555555555556,
                "changed_pixels": 5,
                "visualization_url":
                    "/visualizations/vegetation_2021_2025_change.png",
            }
        ],
        "answer": (
            "NDVI for vegetation changed from "
            "0.4201 in 2021 to 0.3091 in 2025. "
            "The mean change was -0.1110."
        ),
    }

    evidence = build_evidence(
        backend_result
    )

    # ---------------------------------------------------------
    # VLM
    # ---------------------------------------------------------

    print("\nLoading VLM...")

    vlm = VLM()

    print(
        "Sending S2 + S1 + change map + evidence..."
    )

    images = {
    "before": before,
    "after": after,
    "s1_composite": s1_composite,
    }

    if change_map is not None:
        images["change_map"] = change_map

    answer = vlm.generate(
        question=QUESTION,
        evidence=evidence,
        images=images,
    )

    # ---------------------------------------------------------
    # Result
    # ---------------------------------------------------------

    print("\n" + "=" * 70)
    print("RESULT")
    print("=" * 70)

    print("\nQUESTION:")
    print(QUESTION)

    print("\nVLM ANSWER:")
    print(answer)


if __name__ == "__main__":
    main()